#!/bin/bash

echo "========================================="
echo "🚀 Expo在线构建 - 完整指南"
echo "========================================="
echo ""
echo "我已经为你准备好了所有配置文件！"
echo "现在请按照以下步骤操作：" 
echo ""

echo "📋 步骤1: 安装Expo CLI工具"
echo "----------------------------------------"
echo "在终端运行："
echo ""
echo "  npm install -g eas-cli"
echo ""
echo "等待安装完成（约1-2分钟）"
echo ""
read -p "按回车键继续到步骤2..."
echo ""

echo "📋 步骤2: 注册/登录Expo账号"
echo "----------------------------------------"
echo "在终端运行："
echo ""
echo "  eas login"
echo ""
echo "如果你还没有账号："
echo "  1. 访问 https://expo.dev/signup 注册（免费）"
echo "  2. 填写邮箱和密码"
echo "  3. 验证邮箱"
echo "  4. 然后回来运行 eas login"
echo ""
echo "如果已有账号："
echo "  输入邮箱和密码登录"
echo ""
read -p "按回车键继续到步骤3..."
echo ""

echo "📋 步骤3: 初始化项目"
echo "----------------------------------------"
echo "在终端运行："
echo ""
echo "  cd /Users/myc/CodeBuddy/20260209021715"
echo "  eas build:configure"
echo ""
echo "如果询问是否创建项目，选择 Yes"
echo ""
read -p "按回车键继续到步骤4..."
echo ""

echo "📋 步骤4: 开始构建APK"
echo "----------------------------------------"
echo "在终端运行："
echo ""
echo "  eas build --platform android --profile preview"
echo ""
echo "⏳ 构建过程："
echo "  1. 上传代码到Expo服务器（1-2分钟）"
echo "  2. 云端安装依赖（3-5分钟）"
echo "  3. 编译生成APK（5-10分钟）"
echo "  总计：约10-15分钟"
echo ""
echo "💡 提示："
echo "  - 你可以关闭终端，构建会继续进行"
echo "  - 完成后会收到邮件通知"
echo "  - 可以在 https://expo.dev 查看构建状态"
echo ""
read -p "按回车键继续到步骤5..."
echo ""

echo "📋 步骤5: 下载APK"
echo "----------------------------------------"
echo "构建完成后有3种下载方式："
echo ""
echo "方式1: 命令行显示的链接"
echo "  - 终端会显示一个下载链接"
echo "  - 复制链接在浏览器打开下载"
echo ""
echo "方式2: 邮件通知"
echo "  - 查看注册邮箱"
echo "  - 点击邮件中的下载链接"
echo ""
echo "方式3: Expo网站"
echo "  - 访问 https://expo.dev/accounts/[你的用户名]/projects/bill-tracker-app/builds"
echo "  - 找到最新的构建"
echo "  - 点击下载按钮"
echo ""
echo "方式4: 手机扫码（最方便）"
echo "  - 用手机扫描终端显示的二维码"
echo "  - 直接在手机上下载并安装"
echo ""

echo ""
echo "========================================="
echo "✅ 准备工作完成！"
echo "========================================="
echo ""
echo "现在开始执行上面的步骤吧！"
echo ""
echo "💡 常见问题："
echo ""
echo "Q: 构建失败怎么办？"
echo "A: 查看错误信息，通常是依赖问题。告诉我错误信息，我帮你解决。"
echo ""
echo "Q: 免费额度够用吗？"
echo "A: 每月30次构建，个人使用完全够。"
echo ""
echo "Q: 可以取消构建吗？"
echo "A: 可以，在 expo.dev 网站上取消。"
echo ""
echo "Q: APK能直接安装吗？"
echo "A: 可以！下载后传到手机直接安装。"
echo ""
echo "========================================="
echo "🆘 需要帮助？"
echo "========================================="
echo ""
echo "如果遇到任何问题："
echo "1. 截图或复制错误信息"
echo "2. 告诉我卡在哪一步"
echo "3. 我会帮你解决！"
echo ""
echo "现在开始吧！祝你成功！🎉"
echo ""
